GET http://localhost:3000/todos?offset=2

###
GET http://localhost:3000/todos/2

###
POST http://localhost:3000/todos
Content-Type: application/json

{
  "text": ""
}

###
GET http://localhost:3000/todos

###
GET http://localhost:3000/fibonacci

###
GET http://localhost:3000/fibonacci/8

###
POST http://localhost:3000/message
Content-Type: application/json

{
  "sender": "BB",
  "message": "Hello"
}

###
PUT http://localhost:3000/todos/2
Content-Type: application/json

{
  "text": "Szalámit venni"
}

###
DELETE http://localhost:3000/todos/1

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "maria",
  "password": "guess"
}

###
GET http://localhost:3000/auth/profile
Authorization: Bearer

###
GET http://localhost:3000/auth/admin
Authorization: Bearer